/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktek28052024;

/**
 *
 * @author user
 * 
*/

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class CalculatorEx extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorEx
     */
    public CalculatorEx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    


    // Komponen-komponen
    private JTextField display;
    private JButton[] numberButtons;
    private JButton[] functionButtons;
    private JButton addButton, subButton, mulButton, divButton, equButton, clrButton;
    private JPanel panel;

    // Variabel untuk perhitungan
    private double num1, num2, result;
    private char operator;

    // Konstruktor
//    public Calculator() {
        // Inisialisasi frame
//        setTitle("Calculator");
//        setSize(300, 400);
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//        setResizable(false);
//
//        // Inisialisasi komponen
//        display = new JTextField();
//        display.setEditable(false);
//        display.setHorizontalAlignment(JTextField.RIGHT);
//
//        numberButtons = new JButton[10];
//        for (int i = 0; i < 10; i++) {
//            numberButtons[i] = new JButton(String.valueOf(i));
//            numberButtons[i].addActionListener((ActionListener) this);
//        }
//
//        functionButtons = new JButton[5];
//        addButton = new JButton("+");
//        subButton = new JButton("-");
//        mulButton = new JButton("*");
//        divButton = new JButton("/");
//        equButton = new JButton("=");
//        clrButton = new JButton("C");
//
//        functionButtons[0] = addButton;
//        functionButtons[1] = subButton;
//        functionButtons[2] = mulButton;
//        functionButtons[3] = divButton;
//        functionButtons[4] = equButton;
//
//        for (JButton button : functionButtons) {
//            button.addActionListener((ActionListener) this);
//        }
//
//        clrButton.addActionListener((ActionListener) this);
//
//        // Panel untuk menempatkan tombol-tombol
//        panel = new JPanel();
//        panel.setLayout(new GridLayout(4, 4, 10, 10));
//
//        panel.add(numberButtons[1]);
//        panel.add(numberButtons[2]);
//        panel.add(numberButtons[3]);
//        panel.add(addButton);
//        panel.add(numberButtons[4]);
//        panel.add(numberButtons[5]);
//        panel.add(numberButtons[6]);
//        panel.add(subButton);
//        panel.add(numberButtons[7]);
//        panel.add(numberButtons[8]);
//        panel.add(numberButtons[9]);
//        panel.add(mulButton);
//        panel.add(numberButtons[0]);
//        panel.add(clrButton);
//        panel.add(equButton);
//        panel.add(divButton);
//
//        // Menempatkan komponen-komponen ke frame
//        setLayout(new BorderLayout());
//        add(display, BorderLayout.NORTH);
//        add(panel, BorderLayout.CENTER);
//
//        // Menampilkan frame
//        setVisible(true);
//    }
//
//    // Method untuk melakukan perhitungan
//    private void calculate() {
//        switch (operator) {
//            case '+':
//                result = num1 + num2;
//                break;
//            case '-':
//                result = num1 - num2;
//                break;
//            case '*':
//                result = num1 * num2;
//                break;
//            case '/':
//                if (num2 != 0) {
//                    result = num1 / num2;
//                } else {
//                    display.setText("Error");
//                    return;
//                }
//                break;
//        }
//        display.setText(String.valueOf(result));
//    }
//
//    // Method untuk mengatur aksi tombol
//    public void actionPerformed(ActionEvent e) {
//        Object source = e.getSource();
//
//        for (int i = 0; i < 10; i++) {
//            if (source == numberButtons[i]) {
//                display.setText(display.getText() + i);
//                return;
//            }
//        }
//
//        if (source == addButton) {
//            num1 = Double.parseDouble(display.getText());
//            operator = '+';
//            display.setText("");
//        } else if (source == subButton) {
//            num1 = Double.parseDouble(display.getText());
//            operator = '-';
//            display.setText("");
//        } else if (source == mulButton) {
//            num1 = Double.parseDouble(display.getText());
//            operator = '*';
//            display.setText("");
//        } else if (source == divButton) {
//            num1 = Double.parseDouble(display.getText());
//            operator = '/';
//            display.setText("");
//        } else if (source == equButton) {
//            num2 = Double.parseDouble(display.getText());
//            calculate();
//        } else if (source == clrButton) {
//            display.setText("");
//        }
//    }
//
//    // Method utama
//    public static void main(String[] args) {
//        new Calculator();
//    }
//    
    
}

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


